# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-28 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pgn',
            field=models.TextField(),
        ),
    ]
